<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personal Health Care Plan</title>
    <style>
        @font-face { font-family: 'Roboto'; src: url('https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2') format('woff2'); }
        body { font-family: 'Roboto', sans-serif; font-size: 14px; color: #333; line-height: 1.6; margin: 0; padding: 0; }

        .header { background: #0f766e; color: white; padding: 25px 40px; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; }
        .section { padding: 20px 40px; }
        .section-title { font-size: 16px; font-weight: bold; border-bottom: 2px solid #bbf7d0; padding-bottom: 8px; margin-bottom: 20px; color: #166534; text-transform: uppercase; }

        /* Result Box Styling */
        .result-box { padding: 20px; text-align: center; border-radius: 8px; margin-bottom: 30px; border: 1px solid; }
        .result-diabetic { background-color: #fef2f2; border-color: #fecaca; color: #991b1b; }
        .result-healthy { background-color: #f0fdf4; border-color: #bbf7d0; color: #166534; }
        .result-title { font-size: 20px; font-weight: bold; margin-bottom: 5px; }

        .advice-list li { margin-bottom: 10px; color: #475569; }
        .advice-box { background: #f8fafc; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; }
        .footer { padding: 15px 40px; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
    </style>
</head>
<body>

    @php
        $result = json_decode($patient->result, true);

        // Voting Logic to determine final status
        $finalPrediction = 'Pending';
        if (isset($result['predictions']) && is_array($result['predictions'])) {
            $votes = collect($result['predictions'])->map(fn($v) => strtolower(trim($v)));
            $diabeticCount = $votes->filter(fn($v) => $v === 'diabetic')->count();
            $nonCount = $votes->filter(fn($v) => $v === 'non-diabetic')->count();
            $finalPrediction = ($diabeticCount > $nonCount) ? 'Diabetic' : 'Non-Diabetic';
        }
    @endphp

    <div class="header">
        <h1>PERSONAL HEALTH CARE PLAN</h1>
        <p>Patient: {{ $patient->name }} | Date: {{ date('F d, Y') }}</p>
    </div>

    <div class="section">
        <div class="section-title" style="color: #0f766e; border-color: #0f766e;">Your Diagnosis Summary</div>

        @if($finalPrediction === 'Diabetic')
            <div class="result-box result-diabetic">
                <div class="result-title">⚠️ High Risk Indication</div>
                <p style="margin-top: 5px;">Our analysis suggests a strong need for immediate medical review.</p>
            </div>

            <div class="section-title">Essential Action Plan</div>
            <div class="advice-box">
                <ul class="advice-list">
                    <li><strong>Immediate Consultation:</strong> Please schedule a visit with an Endocrinologist within 3 days.</li>
                    <li><strong>Dietary Changes:</strong> Immediately eliminate all added sugar and heavily processed carbohydrates (white rice, bread).</li>
                    <li><strong>Daily Monitoring:</strong> Begin regular glucose level monitoring as advised by your clinic.</li>
                    <li><strong>Hydration & Activity:</strong> Increase water intake and commit to 30 minutes of daily activity (e.g., walking).</li>
                </ul>
            </div>

        @else
            <div class="result-box result-healthy">
                <div class="result-title">✅ Low Risk (Healthy Status)</div>
                <p style="margin-top: 5px;">Your vitals are currently within the safe range. Keep up the good work!</p>
            </div>

            <div class="section-title">Prevention & Maintenance Guide</div>
            <div class="advice-box">
                <ul class="advice-list">
                    <li><strong>Balanced Diet:</strong> Focus on maintaining a whole-foods diet rich in fiber and lean protein.</li>
                    <li><strong>Weight Management:</strong> Ensure your BMI stays below 25. Regular exercise is key.</li>
                    <li><strong>Avoidance:</strong> Strictly limit sugary drinks and processed snacks to prevent future risks.</li>
                    <li><strong>Routine Checkups:</strong> Schedule a full metabolic panel checkup every 6 months for proactive health management.</li>
                </ul>
            </div>
        @endif

        <div style="margin-top: 50px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px;">
            This report is for general guidance and health awareness only. Please follow your doctor's specific instructions.
        </div>
    </div>

    <div class="footer">
        Generated by Diabetes Care AI System • {{ date('F d, Y') }}
    </div>
</body>
</html>
